[project]
name = "anticoagulant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anticoagulant",
    "pandas>=2.2.3",
    "streamlit>=1.39.0",
]

[tool.uv.sources]
anticoagulant = { workspace = true }
